import streamlit as st

st.title("Author's Reflections")

st.text('This project helped me grow tremendously, both technically and in how I approach data projects.')

st.text('On the technical side, I became much more confident in using Streamlit, especially multi-page apps, data imports, and converting Jupyter notebooks into clean .py files. I learned how to build interactive dashboards, manage variable naming, and structure my code for clarity and reuse. I also got more comfortable with wrangling public datasets, creating graphs and tables, and exporting data using tools like .to_csv() to better move results from Jupyter into Streamlit. Learning how to use .to_csv() was a turning point in making the transition between notebooks and the dashboard more efficient.')

st.text('One of my biggest breakthroughs came from how I approached planning and analysis. I made a conscious effort to organize my workflow better, using planning pages, cleaning datasets upfront, and exploring raw files in Excel before jumping into Python. This was especially important when merging two large datasets into a third, unified one. Understanding the structure ahead of time made the analysis much smoother and helped me pinpoint hidden issues before diving into the deep end.')

st.text('Beyond the tools, this project gave me confidence. I no longer feel lost when working with Streamlit or managing datasets across different formats. At the same time, I recognize areas where I still want to grow, like developing stronger research questions, applying SciPy for statistical analysis, and refining my use of Plotly for more advanced visualizations.')

st.text('The deployment process for this dashboard turned out to be one of the most unexpectedly complex and time-consuming parts of the entire project. What began as a routine attempt to share my work online quickly evolved into nearly seven hours of continuous debugging and problem-solving. I encountered multiple technical obstacles — GeoPandas failed to load shapefiles properly, which required converting all spatial data to .geojson format. Several key data files exceeded GitHub’s 50 MB upload limit, so I had to store them in Google Drive and integrate a custom data_loader.py script (with guidance from ChatGPT) to download and read them at runtime. I also struggled with inconsistent relative file paths, which worked locally but broke on Streamlit Cloud due to differences in how each environment handles execution. To add to the challenge, the Streamlit website itself briefly went down during deployment, forcing me to resync my GitHub account and reconfigure the app. Although the process was at times frustrating, it taught me a great deal about the technical nuances of deploying interactive web apps and the importance of maintaining clear structure and flexibility in my code. In the end, the experience strengthened my problem-solving skills and made seeing the final product live even more rewarding.')

st.text('This dashboard is evidence of how much I have improved since my earlier projects, and a great foundation for the public health data analysis I hope to do next. I want to keep improving my setup and skills to hone in on more advanced statistical analyses while being able to handle more complex datasets.')